apiVersion: v1
kind: Service
metadata:
    name: ftsfront
spec:
    type: LoadBalancer
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 5173
    selector:
        app: ftsfront